// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwKuRVu5-g1bUETRsFAk89X7DdZdsgJVo',
    appId: '1:269243618765:web:82b9f70449a99cdda0e084',
    messagingSenderId: '269243618765',
    projectId: 'mutualaid-group',
    authDomain: 'mutualaid-group.firebaseapp.com',
    storageBucket: 'mutualaid-group.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1sWNgbjkhYC29r0bMRTM8PB6jssvEAsA',
    appId: '1:269243618765:android:5193746da805a836a0e084',
    messagingSenderId: '269243618765',
    projectId: 'mutualaid-group',
    storageBucket: 'mutualaid-group.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5KFm905IMSMosaQjn02ND16vxsxAa_NU',
    appId: '1:269243618765:ios:6a035c0e3d0b144fa0e084',
    messagingSenderId: '269243618765',
    projectId: 'mutualaid-group',
    storageBucket: 'mutualaid-group.appspot.com',
    iosClientId: '269243618765-ub172nc829f18f8ifu4luifi20m69h48.apps.googleusercontent.com',
    iosBundleId: 'group.mutualaid.mutualaid',
  );
}
